### ISSUE TITLE
The validation message lacks clarity

### ISSUE THREAD

**Issue by ragingdave** [korridor/laravel-model-validation-rules#10]
The validation messages are very non-descript and with the ability to set a closure callback, just "doesn't exist" in many cases might not be enough to get the right message across.

Potentially being able to either set on the fly the message optionally, or using some fluent way of specifying the message would make this far more usable from an end user's perspective.

Something like 
```
(new ExistsEloquent(Post::class))->withMessage('Post is broke')
```

This would be useful for situations where potentially a relation check is used to confirm existence like:
```
new ExistsEloquent(Post::class, null, fn ($q) => $q->whereHas('comments'))->withMessage('Post is missing comments')
```

This is significantly clearer than just "This resource doesn't exist".

**Comment by korridor** [comment]
Thank you for this feature request!
I think this is a very good idea and I will try to create a pull request in the next days.

**Comment by korridor** [comment]
I'm very sorry I completely overlooked your pull request and now I've already developed something myself. I just created this pull request #12. Please have a look, if this solves your problems.

**Comment by ragingdave** [comment]
Looks like what you added will work for me as it's very similar to how I solved it as well (only so many ways to skin a cat lol). would love to see this in the next version!

**Comment by korridor** [comment]
Just made a new release (`2.1.0`) with the new changes. Thanks again for your feedback!
